# Generated by Django 3.0.3 on 2020-02-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juhe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=[], max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='constellation',
            field=models.CharField(default=[], max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='stock',
            field=models.CharField(default=[], max_length=360),
        ),
    ]
