# Generated by Django 3.0.3 on 2020-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juhe', '0002_auto_20200227_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='user',
            name='constellation',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='user',
            name='stock',
            field=models.TextField(default=[]),
        ),
    ]
