# Generated by Django 3.0.3 on 2020-03-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juhe', '0004_user_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='menu',
        ),
    ]
