# Generated by Django 3.0.3 on 2020-03-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juhe', '0005_remove_user_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='test')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='menu',
            field=models.ManyToManyField(to='juhe.App'),
        ),
    ]
