# Generated by Django 3.0.3 on 2020-03-09 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juhe', '0006_auto_20200309_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coll',
        ),
    ]
