# Generated by Django 3.0.3 on 2020-03-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juhe', '0007_remove_user_coll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='menu',
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
