# Generated by Django 3.0.3 on 2020-03-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juhe', '0002_user_coll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='menu',
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
