# Generated by Django 3.0.3 on 2020-03-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('juhe', '0003_auto_20200309_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='menu',
            field=models.ManyToManyField(to='api.App'),
        ),
    ]
